import type { Metadata } from "next";
import "./globals.css";
import SideMenu from "@/components/SideMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="flex flex-col bg-gray-100 text-customGray min-h-screen">
        <SideMenu />
        {children}
      </body>
    </html>
  );
}
